version: '3.8'

services:
  or-postgres:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    container_name: or-postgres
    command: powershell -Command "Start-Process 'C:\\PostgreSQL\\bin\\postgres.exe' -ArgumentList '-D', 'C:\\PostgreSQL\\data' -Wait"
    volumes:
      - postgres-data:C:\\PostgreSQL\\data
    environment:
      - POSTGRES_USER=openremote
      - POSTGRES_PASSWORD=openremote
      - POSTGRES_DB=openremote
    networks:
      - openremote-net

  or-keycloak:
    image: jboss/keycloak:latest
    container_name: or-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
    networks:
      - openremote-net

  or-manager:
    build:
      context: ./manager
      dockerfile: Dockerfile.windows
    container_name: or-manager
    depends_on:
      - or-postgres
      - or-keycloak
    ports:
      - "8081:8080"
    networks:
      - openremote-net

volumes:
  postgres-data:

networks:
  openremote-net:
